
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EXP LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : factor EXP unaryfactor : unaryunary : MINUS unaryunary : NUMBERunary : LPAREN expression RPARENunary : NUMBER LPAREN expression RPAREN'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,],[3,9,-3,3,-6,-8,-10,3,3,3,3,3,-9,3,3,9,-1,-2,-4,-5,-7,9,-11,-12,]),'NUMBER':([0,3,7,8,9,10,11,13,14,],[6,6,6,6,6,6,6,6,6,]),'LPAREN':([0,3,6,7,8,9,10,11,13,14,],[7,7,14,7,7,7,7,7,7,7,]),'$end':([1,2,4,5,6,12,16,17,18,19,20,22,23,],[0,-3,-6,-8,-10,-9,-1,-2,-4,-5,-7,-11,-12,]),'PLUS':([1,2,4,5,6,12,15,16,17,18,19,20,21,22,23,],[8,-3,-6,-8,-10,-9,8,-1,-2,-4,-5,-7,8,-11,-12,]),'RPAREN':([2,4,5,6,12,15,16,17,18,19,20,21,22,23,],[-3,-6,-8,-10,-9,22,-1,-2,-4,-5,-7,23,-11,-12,]),'TIMES':([2,4,5,6,12,16,17,18,19,20,22,23,],[10,-6,-8,-10,-9,10,10,-4,-5,-7,-11,-12,]),'DIVIDE':([2,4,5,6,12,16,17,18,19,20,22,23,],[11,-6,-8,-10,-9,11,11,-4,-5,-7,-11,-12,]),'EXP':([4,5,6,12,18,19,20,22,23,],[13,-8,-10,-9,13,13,-7,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,14,],[1,15,21,]),'term':([0,7,8,9,14,],[2,2,16,17,2,]),'factor':([0,7,8,9,10,11,14,],[4,4,4,4,18,19,4,]),'unary':([0,3,7,8,9,10,11,13,14,],[5,12,5,5,5,5,5,20,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','tareas4.py',37),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','tareas4.py',41),
  ('expression -> term','expression',1,'p_expression_term','tareas4.py',45),
  ('term -> term TIMES factor','term',3,'p_term_times','tareas4.py',49),
  ('term -> term DIVIDE factor','term',3,'p_term_divide','tareas4.py',53),
  ('term -> factor','term',1,'p_term_factor','tareas4.py',57),
  ('factor -> factor EXP unary','factor',3,'p_factor_exp','tareas4.py',61),
  ('factor -> unary','factor',1,'p_factor_unary','tareas4.py',65),
  ('unary -> MINUS unary','unary',2,'p_unary','tareas4.py',69),
  ('unary -> NUMBER','unary',1,'p_unary_number','tareas4.py',73),
  ('unary -> LPAREN expression RPAREN','unary',3,'p_unary_expr','tareas4.py',77),
  ('unary -> NUMBER LPAREN expression RPAREN','unary',4,'p_unary_implicit_mult','tareas4.py',81),
]
